# path will be relative to this package root folder
path_relative: False # use False when providing absolute filepaths
source_path: "/home/klaxalk/timepix_data/in"
result_path: "/home/klaxalk/timepix_data/out"
classifier_pipeline_path: "/home/klaxalk/git/radiation_core/ros_packages/classification/pipelines/vzlusat-1.joblib_p3"

# delimiter for data on the input
input_delimiter: ' '
